// 오피스 도구 7종의 정의(이름·설명·인자 형식·실행) 한 곳 — 아르고 본체 에이전트(chat.mjs makeCrewServer), argo office CLI(src/office-cli.mjs),
// argo office mcp(Claude Code·Codex 등이 붙는 MCP 서버)가 같이 쓴다(유건 10/10 "클로드코드든 코덱스든 아르고든 연결해서 쓸 수 있어야").
// 실행 o = { ctx, crew, crewName, lang, ownerId } — 관문(누가 보는 자리인가·주인 세션인가)은 각 처리기와 office-audience.mjs가 판정한다(CLI는 cliContext).
// guest = 손님 턴 거절 문구(본체만 쓴다). 인자 형식은 chat.mjs에 있던 것을 글자 그대로 옮겼다 — 본체 도구 목록이 바뀌지 않게(test/office-cli-tools.test.mjs C8).
import { z } from 'zod';
import { calendarTool, calendarDescription } from './office-calendar.mjs';
import { companyTool, companyDescription } from './office-company.mjs';
import { filesTool, filesDescription } from './office-files.mjs';
import { workTool, workDescription } from './office-work.mjs';
import { dealsTool, dealsDescription } from './office-deals.mjs';
import { mailTool, mailDescription } from './office-mail.mjs';
import { briefingTool, briefingDescription } from './office-briefing.mjs';

export function officeToolSpecs(lang = 'ko') {
  return [
    {
      name: 'calendar',
      description: calendarDescription(lang),
      guest: { ko: '주인의 일정 보기·고치기', en: 'Reading or changing the owner\'s calendar' },
      shape: {
        action: z.enum(['list', 'create', 'update', 'delete']),
        from: z.string().optional().describe('list: 시작 날짜 YYYY-MM-DD(한국 날짜)'),
        to: z.string().optional().describe('list: 끝 날짜 YYYY-MM-DD(포함, from부터 최대 62일)'),
        id: z.string().optional().describe('update·delete: list가 보여 준 일정 id'),
        day: z.string().optional().describe('update·delete: list가 보여 준 그 줄의 날짜 YYYY-MM-DD(반복이면 회차 날짜)'),
        scope: z.enum(['this', 'following', 'all']).optional().describe('반복 일정 update·delete: this=이 회차만, following=이 회차 및 이후, all=모든 회차'),
        calendar: z.enum(['personal', 'org']).optional().describe('personal=개인(기본), org=지금 메신저 조직'),
        visibility: z.enum(['org', 'private']).optional().describe('조직 일정의 공개 범위: org=조직 전체(기본), private=나만'),
        title: z.string().optional(),
        start: z.string().optional().describe('YYYY-MM-DD(종일) · YYYY-MM-DDTHH:MM(한국 시간) · 시간대 포함 ISO'),
        end: z.string().optional().describe('종일이면 끝날 YYYY-MM-DD(포함), 시간 일정이면 YYYY-MM-DDTHH:MM·ISO·HH:MM'),
        all_day: z.boolean().optional(),
        note: z.string().optional(), location: z.string().optional(), category: z.string().optional(),
        repeat: z.enum(['none', 'daily', 'weekly', 'monthly']).optional().describe('반복: 매주는 시작 요일, 매월은 시작 날짜'),
        repeat_interval: z.number().optional().describe('반복 간격 1~99(기본 1)'),
        repeat_until: z.string().optional().describe('반복 종료일 YYYY-MM-DD(포함)'),
      },
      run: (args, o = {}) => calendarTool(args, { ctx: o.ctx, crew: o.crew, lang: o.lang, ownerId: o.ownerId }),
    },
    {
      name: 'office',
      description: companyDescription(lang),
      guest: { ko: '회사 기록 보기·고치기', en: 'Reading or changing company records' },
      shape: {
        action: z.enum(['company', 'company_set', 'people', 'evals', 'eval_add']),
        id: z.string().optional().describe('company_set: 고칠 항목 id(company가 보여 준 것)'),
        label: z.string().optional(), value: z.string().optional(), notes: z.string().optional(),
        category: z.enum(['basic', 'bank', 'contact', 'tax', 'other']).optional(),
        key: z.string().optional().describe('서식 칸: name·reg_name·ceo·biz_no·corp_no·open_date·address·biz_type·biz_item·manager·phone·fax·email·tax_email·website'),
        status: z.enum(['active', 'left', 'all']).optional().describe('people: 재직(기본)·퇴사·전체'),
        scope: z.enum(['week', 'month', 'year']).optional(), subject: z.string().optional().describe('evals: 대상 이름으로 거르기'),
        period_day: z.string().optional().describe('eval_add: 그 기간 안의 아무 날 YYYY-MM-DD(비우면 오늘)'),
        subject_kind: z.enum(['person', 'crew']).optional(), subject_user: z.string().optional(), subject_name: z.string().optional(), subject_type: z.enum(['ceo', 'staff']).optional(),
        title: z.string().optional(), performance: z.number().optional(), quality: z.number().optional(), productivity: z.number().optional(), expertise: z.number().optional(), collaboration: z.number().optional(), total: z.number().optional(),
        review: z.string().optional(), work: z.string().optional(), achievements: z.string().optional(),
      },
      run: (args, o = {}) => companyTool(args, { ctx: o.ctx, crew: o.crew, lang: o.lang, ownerId: o.ownerId }),
    },
    {
      name: 'office_files',
      description: filesDescription(lang),
      guest: { ko: '오피스 문서함 보기·올리기', en: 'Reading or changing Office files' },
      shape: {
        action: z.enum(['files', 'file_read', 'attach', 'drive', 'drive_import', 'drive_mkdir', 'drive_export']),
        q: z.string().optional().describe('files: 제목·파일명·읽은 글자·태그 검색 / drive: 드라이브 이름 검색'),
        id: z.string().optional().describe('file_read·drive_export: 문서함 파일 id(files가 보여 준 것)'),
        customer_id: z.string().optional().describe('files: 그 거래처 파일만 / attach·drive_import: 붙일 거래처 id(업무 › 거래처)'),
        path: z.string().optional().describe('attach: 올릴 파일 경로(작업 공간 안 — 예: vault/files/명함.png)'),
        title: z.string().optional().describe('attach: 문서함에 보일 이름(비우면 파일 이름)'),
        category: z.enum(['quote', 'contract', 'bizcert', 'card', 'bankbook', 'evidence', 'archive', 'general']).optional(),
        drive_id: z.string().optional().describe('drive_import: drive가 보여 준 드라이브 파일 id'),
        folder: z.string().optional().describe('drive: 볼 드라이브 폴더 id / drive_mkdir: 부모 폴더 id / drive_export: 보낼 드라이브 폴더 id'),
        view: z.enum(['home', 'mydrive', 'shared', 'drives', 'starred']).optional(),
        name: z.string().optional().describe('drive_mkdir: 새 폴더 이름'),
      },
      run: (args, o = {}) => filesTool(args, { ctx: o.ctx, crew: o.crew, lang: o.lang, ownerId: o.ownerId }),
    },
    {
      name: 'office_work',
      description: workDescription(lang),
      guest: { ko: '오피스 할 일·페이지 보기·고치기', en: 'Reading or changing Office tasks and pages' },
      shape: {
        action: z.enum(['tasks', 'task_add', 'task_set', 'categories', 'pages', 'page_read', 'page_add', 'page_edit']),
        id: z.string().optional().describe('task_set: 할 일 id / page_read·page_edit: 페이지 id(tasks·pages가 보여 준 것)'),
        who: z.enum(['me', 'all']).optional().describe('tasks: me=주인이 맡은 일(기본), all=주인이 볼 수 있는 모든 일(1:1에서만)'),
        status: z.enum(['todo', 'doing', 'hold', 'done']).optional().describe('tasks: 거르기 / task_add·task_set: todo 할 일 · doing 진행 중 · hold 보류 · done 끝내기(task_set)'),
        overdue: z.boolean().optional().describe('tasks: 기한 지난 일만'),
        category: z.string().optional().describe('분류 이름 또는 id(categories가 보여 준 것), none=미분류'),
        q: z.string().optional().describe('tasks: 제목·메모 검색 / pages: 제목 검색'),
        title: z.string().optional(),
        priority: z.enum(['high', 'normal', 'low']).optional(),
        due_on: z.string().optional().describe('기한 YYYY-MM-DD(task_set에서 none=지우기)'),
        starts_on: z.string().optional().describe('시작일 YYYY-MM-DD(기한보다 늦을 수 없다, task_set에서 none=지우기)'),
        note: z.string().optional().describe('할 일 메모 — task_set은 기존 메모 뒤에 덧붙인다'),
        note_mode: z.enum(['append', 'replace']).optional().describe('task_set 메모: append 덧붙이기(기본) · replace 통째로 바꾸기'),
        parent_id: z.string().optional().describe('page_add: 상위 페이지 id(비우면 최상위 — 관리자만)'),
        text: z.string().optional().describe('page_add·page_edit 본문: # 제목, - 목록, 1. 번호, - [ ] 체크, > 인용, --- 구분선, 나머지 줄은 문단'),
        mode: z.enum(['append', 'replace']).optional().describe('page_edit: append 끝에 덧붙이기(기본) · replace 본문 바꾸기'),
      },
      run: (args, o = {}) => workTool(args, { ctx: o.ctx, crew: o.crew, crewName: o.crewName, lang: o.lang, ownerId: o.ownerId }),
    },
    {
      name: 'office_deals',
      description: dealsDescription(lang),
      guest: { ko: '오피스 거래처·거래 보기·고치기', en: 'Reading or changing Office customers and deals' },
      shape: {
        action: z.enum(['customers', 'customer_add', 'customer_set', 'deals', 'deal_add', 'deal_next', 'deal_due']),
        id: z.string().optional().describe('customers: 그 거래처 자세히 / customer_set: 거래처 id / deal_next·deal_due: 거래 id'),
        q: z.string().optional().describe('customers: 이름·담당·메일·전화·대표·사업자번호 검색 / deals: 건명 검색'),
        archived: z.boolean().optional().describe('customers: 보관함 보기'),
        name: z.string().optional(), manager: z.string().optional(), phone: z.string().optional(), email: z.string().optional(),
        ceo: z.string().optional(), biz_no: z.string().optional(), address: z.string().optional(), account: z.string().optional().describe('거래처 계좌(1:1에서만)'),
        category: z.enum(['customer', 'partner', 'supplier', 'other']).optional(),
        status: z.enum(['active', 'hold', 'closed']).optional().describe('거래처 상태'),
        notes: z.string().optional().describe('거래처 메모 — customer_set은 기존 메모 뒤에 덧붙인다. 출처(명함·계약서 등)를 남겨라'),
        customer_id: z.string().optional().describe('deals: 그 거래처 거래만 / deal_add: 거래처 id'),
        stage: z.enum(['quote', 'contract', 'invoice', 'paid', 'cancelled', 'open']).optional().describe('deals 거르기: open=입금 완료·취소 전'),
        overdue: z.boolean().optional().describe('deals: 입금 지연만'),
        title: z.string().optional().describe('deal_add: 건명'),
        lines: z.array(z.object({
          item: z.string().describe('품목 이름(없으면 서비스 품목으로 만든다) 또는 품목 id'),
          unit_price: z.number().describe('단가(원, 부가세 별도, 정수)'),
          quantity: z.number().optional().describe('수량(기본 1)'),
          tax_type: z.enum(['taxable', 'zero', 'exempt']).optional().describe('과세(기본)·영세율·면세'),
        })).optional().describe('deal_add: 품목 줄 — 금액은 견적서·계약서 같은 실제 근거로만'),
        due_on: z.string().optional().describe('입금 예정일 YYYY-MM-DD(deal_due에서 none=지우기)'),
        date: z.string().optional().describe('deal_add: 견적일 / deal_next: 그 단계 날짜 YYYY-MM-DD(비우면 지금)'),
        to: z.enum(['contract', 'invoice', 'paid', 'cancel']).optional().describe('deal_next: contract 계약 확정 · invoice 계산서 발행 기록 · paid 입금 기록 · cancel 취소'),
        amount: z.number().optional().describe('deal_next invoice·paid: 금액(원, 부가세 포함, 비우면 남은 전부)'),
        note: z.string().optional().describe('deal_next: 기록에 남길 메모'),
        confirm_duplicate: z.boolean().optional().describe('customer_add·deal_add: 비슷한 것이 있다는 안내를 확인하고도 새로 만들 때만 true'),
      },
      run: (args, o = {}) => dealsTool(args, { ctx: o.ctx, lang: o.lang, ownerId: o.ownerId }),
    },
    {
      name: 'office_mail',
      description: mailDescription(lang),
      guest: { ko: '주인의 메일 보기·초안 쓰기', en: 'Reading the owner\'s mail or writing drafts' },
      shape: {
        action: z.enum(['mails', 'mail_read', 'mail_draft', 'mail_star']),
        account: z.string().optional().describe('메일 계정 주소(여럿 연결했을 때, 비우면 첫 계정)'),
        folder: z.enum(['inbox', 'unread', 'starred', 'sent', 'drafts', 'archive']).optional(),
        q: z.string().optional().describe('mails: Gmail 검색어(예: from:kim@x.com 세금계산서)'),
        id: z.string().optional().describe('mail_read·mail_star: mails가 보여 준 메일 id'),
        reply_to: z.string().optional().describe('mail_draft: 답장할 메일 id(받는 사람·제목·스레드를 원문에서)'),
        to: z.string().optional(), cc: z.string().optional(), subject: z.string().optional(),
        text: z.string().optional().describe('mail_draft: 본문(글자)'),
        starred: z.boolean().optional().describe('mail_star: false면 별표 떼기'),
      },
      run: (args, o = {}) => mailTool(args, { ctx: o.ctx, lang: o.lang, ownerId: o.ownerId }),
    },
    {
      name: 'office_briefing',
      description: briefingDescription(lang),
      guest: { ko: '주인의 브리핑 읽기·쓰기', en: 'Reading or writing the owner\'s briefings' },
      shape: {
        action: z.enum(['brief_add', 'briefs', 'brief_read']),
        title: z.string().optional(), body: z.string().optional().describe('brief_add: 마크다운 본문(32KB까지)'),
        kind: z.enum(['daily', 'weekly', 'custom']).optional(), period: z.string().optional().describe('brief_add: 기간 표시(예: 2026-10-05, 이번 주)'),
        recipient: z.enum(['owner', 'org']).optional().describe('brief_add: owner(기본, 주인) 또는 org(조직 전체 — 관리자만)'),
        q: z.string().optional().describe('briefs: 제목·본문에서 찾을 글자'), id: z.string().optional().describe('brief_read: briefs가 보여 준 id'),
      },
      run: (args, o = {}) => briefingTool(args, { ctx: o.ctx, crew: o.crewName || o.crew, lang: o.lang, ownerId: o.ownerId }),
    },
  ];
}
