// 반응 이모티콘 — 슬랙식(유건 지시 2026-09-09): hover에 자주 쓰는 2~3개, '반응'은 검색·분류 드롭다운.
// 항목 = [이모티콘, 검색어(한/영 공백 구분)]. 검색은 검색어 부분 일치. 자주 사용은 localStorage 빈도(기기별).
// 2026-10-08 유건 "이모티콘 더 많이" — 69개 → 310개. 새 항목은 Unicode 12.1 이하 코드 포인트만(ZWJ·피부색 없음):
// Emoji 13.0 이상은 Windows 11부터 그려져(Windows 10 일반 배포판은 12.0까지) 네모로 보인다. 예외는 9/9부터 있던 🫡(14.0) 하나 — test/emoji.test.mjs.
// 묶음 제목은 i18n.js 'emoji.<key>'. 같은 이모티콘을 두 묶음에 넣지 않는다(격자 key가 이모티콘이다).
// 다크 바탕(#252525)에서 거의 안 보이는 검은·짙은 회색 글리프(✔️ 🔜 ⚫ 🐾 🎵 🎶 🚲 ➖, 대비 p90 < 2.1)는 새로 넣지 않았다. 원래 있던 ➕만 그대로.
export const EMOJI_GROUPS = [
  { key: 'work', items: [['✅', '확인 완료 check done ok'], ['👀', '보는중 확인 eyes looking'], ['🙌', '만세 좋아 hands celebrate'], ['🙏', '감사 부탁 thanks please pray'], ['➕', '추가 plus one'], ['👏', '박수 clap'], ['💡', '아이디어 idea'], ['🎯', '목표 target'], ['👋', '인사 wave hi'], ['🎉', '축하 party'], ['1️⃣', '하나 one 1'], ['2️⃣', '둘 two 2'], ['3️⃣', '셋 three 3'], ['📣', '공지 announce'], ['⚪', '흰 원 white circle'], ['🔵', '파란 원 blue circle'], ['🔴', '빨간 원 red circle'],
    ['☑️', '체크 확인 완료 check box done'], ['🆗', '오케이 확인 ok button'], ['⏳', '진행중 대기 기다림 hourglass waiting progress'], ['🚧', '작업중 공사 진행중 construction wip'], ['🆕', '새로 신규 new'], ['⏱️', '마감 시간 측정 stopwatch deadline timer'], ['📊', '차트 통계 보고 chart stats report'], ['📈', '상승 증가 성장 chart up increase growth'], ['📉', '하락 감소 chart down decrease'], ['🏁', '완료 끝 결승 finish flag done'], ['🛠️', '수리 고침 도구 fix tools repair'], ['🙋', '손들기 저요 질문 raise hand me question'],
    ['🟢', '초록 원 정상 green circle'], ['🟡', '노란 원 주의 yellow circle'], ['🟠', '주황 원 orange circle'], ['🟣', '보라 원 purple circle'], ['🟤', '갈색 원 brown circle']] },
  { key: 'face', items: [['😀', '웃음 grin'], ['😃', '웃음 smile'], ['😄', '웃음 smile happy'], ['😁', '씨익 grin'], ['😆', '깔깔 laugh'], ['😅', '식은땀 sweat smile'], ['🤣', '데굴 rofl'], ['😂', '눈물 웃음 joy laugh'], ['🙂', '미소 slight smile'], ['🙃', '거꾸로 upside down'], ['😉', '윙크 wink'], ['😊', '수줍 blush'], ['😇', '천사 angel'], ['🥰', '사랑 love'], ['😍', '하트눈 heart eyes'], ['🤩', '별눈 star struck'], ['😘', '뽀뽀 kiss'], ['🤔', '생각 thinking hmm'], ['😮', '놀람 wow surprised'], ['😢', '슬픔 sad cry'], ['😎', '멋짐 cool sunglasses'], ['🥳', '파티 party'], ['😴', '졸림 sleep'], ['🤯', '충격 mind blown'],
    ['😋', '맛있 냠냠 yum delicious'], ['😜', '메롱 장난 wink tongue'], ['🤪', '정신없 엉뚱 zany crazy'], ['🤗', '포옹 안아 hug'], ['🤭', '입가림 킥킥 giggle oops'], ['🤫', '쉿 비밀 shush secret quiet'], ['🤨', '의심 갸웃 suspicious raised eyebrow'], ['😐', '무표정 neutral'], ['😏', '능글 씩 smirk'], ['😒', '시큰둥 불만 unamused'],
    ['🙄', '어이없 눈굴림 eye roll'], ['😬', '어색 으 grimace awkward'], ['😌', '안도 휴 relieved'], ['😔', '시무룩 우울 pensive'], ['🤤', '침 군침 drool'], ['😷', '마스크 아픔 mask sick'], ['🤮', '토 우웩 vomit'], ['🥵', '더움 덥다 hot'], ['🥴', '어질 취함 woozy'], ['😵', '어지러 기절 dizzy'],
    ['🤓', '공부 범생 nerd'], ['🧐', '자세히 탐구 monocle inspect'], ['😕', '헷갈 갸우뚱 confused'], ['😳', '당황 화들짝 flushed embarrassed'], ['🥺', '부탁 글썽 please pleading'], ['😰', '불안 식은땀 anxious'], ['😥', '아쉬움 휴 disappointed relieved'], ['😭', '엉엉 오열 sob crying'], ['😱', '비명 경악 scream shock'], ['😩', '지침 힘듦 weary tired'],
    ['🥱', '하품 지루 yawn bored'], ['😤', '씩씩 콧김 huff triumph'], ['😡', '화남 분노 angry rage'], ['🤬', '욕 격분 cursing'], ['💀', '해골 죽겠다 skull dead'], ['🤡', '광대 clown'], ['👻', '유령 ghost'], ['🤖', '로봇 봇 robot bot'], ['💩', '똥 poop'], ['😶', '할말없음 무언 speechless no mouth']] },
  { key: 'hand', items: [['👍', '좋아요 thumbs up like'], ['👎', '싫어요 thumbs down'], ['👌', '오케이 ok'], ['✌️', '브이 peace'], ['🤞', '행운 fingers crossed'], ['💪', '힘 muscle strong'], ['🤝', '악수 handshake deal'], ['✍️', '작성 writing'], ['🫡', '경례 salute yes sir'], ['🤙', '연락 call me'],
    ['👊', '주먹 파이팅 fist bump'], ['✊', '주먹 단결 raised fist'], ['🤟', '사랑해 love you gesture'], ['🤘', '락 신남 rock on'], ['👈', '왼쪽 이쪽 point left'], ['👉', '오른쪽 저쪽 point right'], ['👆', '위 위에 point up above'], ['👇', '아래 아래에 point down below'], ['☝️', '저요 하나 index up one'], ['✋', '손바닥 멈춤 잠깐 raised hand stop'],
    ['🖐️', '손 펼침 다섯 hand five'], ['👐', '두손 활짝 open hands'], ['🤲', '두손 모음 받기 palms up'], ['🤏', '조금 살짝 pinch little'], ['🙆', '동그라미 좋아요 ok gesture yes'], ['🙅', '엑스 안돼 no gesture'], ['🤷', '글쎄 몰라 shrug'], ['🤦', '아이고 이마짚기 facepalm'], ['🙇', '꾸벅 사과 감사 bow sorry'], ['👂', '귀 듣기 ear listen']] },
  { key: 'heart', items: [['❤️', '하트 빨강 heart love red'], ['🧡', '주황 하트 orange heart'], ['💛', '노랑 하트 yellow heart'], ['💚', '초록 하트 green heart'], ['💙', '파랑 하트 blue heart'], ['💜', '보라 하트 purple heart'], ['🤎', '갈색 하트 brown heart'], ['🖤', '검정 하트 black heart'], ['🤍', '흰 하트 white heart'], ['💔', '상심 깨진 하트 broken heart'],
    ['❣️', '하트 느낌표 heart exclamation'], ['💕', '하트 두개 two hearts'], ['💞', '회전 하트 revolving hearts'], ['💓', '두근 하트 beating heart'], ['💗', '커지는 하트 growing heart'], ['💖', '반짝 하트 sparkling heart'], ['💘', '큐피드 화살 하트 cupid arrow heart'], ['💝', '리본 하트 선물 gift heart'], ['💟', '하트 장식 heart decoration'], ['💌', '편지 연애편지 love letter'], ['💋', '키스 입술 kiss lips']] },
  { key: 'animal', items: [['🐶', '강아지 개 dog puppy'], ['🐱', '고양이 냥 cat'], ['🐰', '토끼 rabbit bunny'], ['🦊', '여우 fox'], ['🐻', '곰 bear'], ['🐼', '판다 panda'], ['🐨', '코알라 koala'], ['🐯', '호랑이 tiger'], ['🦁', '사자 lion'], ['🐷', '돼지 pig'],
    ['🐸', '개구리 frog'], ['🐵', '원숭이 monkey'], ['🙈', '안봐 못본척 see no evil monkey'], ['🙉', '안들려 hear no evil monkey'], ['🙊', '입다물 speak no evil monkey'], ['🐧', '펭귄 penguin'], ['🐤', '병아리 chick'], ['🦉', '부엉이 올빼미 owl'], ['🐺', '늑대 wolf'], ['🦄', '유니콘 unicorn'],
    ['🐝', '꿀벌 벌 bee'], ['🦋', '나비 butterfly'], ['🐢', '거북이 느림 turtle slow'], ['🐙', '문어 octopus'], ['🐳', '고래 whale'], ['🐬', '돌고래 dolphin'], ['🦖', '공룡 티라노 dinosaur t-rex'], ['🐹', '햄스터 hamster'], ['🌸', '벚꽃 꽃 cherry blossom flower'], ['🌹', '장미 rose'],
    ['🌻', '해바라기 sunflower'], ['🌱', '새싹 성장 seedling sprout'], ['🍀', '네잎클로버 행운 clover luck'], ['🍁', '단풍 가을 maple leaf autumn'], ['🌵', '선인장 cactus'], ['🌈', '무지개 rainbow'], ['☀️', '해 맑음 sun sunny'], ['🌙', '달 밤 moon night'], ['❄️', '눈 겨울 snowflake winter'], ['⚡', '번개 빠름 lightning fast'], ['🌊', '파도 바다 wave ocean']] },
  { key: 'food', items: [['🍎', '사과 apple'], ['🍊', '귤 오렌지 tangerine orange'], ['🍋', '레몬 lemon'], ['🍌', '바나나 banana'], ['🍉', '수박 watermelon'], ['🍇', '포도 grapes'], ['🍓', '딸기 strawberry'], ['🍑', '복숭아 peach'], ['🥑', '아보카도 avocado'], ['🍞', '빵 식빵 bread'],
    ['🥐', '크루아상 croissant'], ['🍳', '계란 요리 fried egg cooking'], ['🍔', '햄버거 burger'], ['🍟', '감자튀김 fries'], ['🍕', '피자 pizza'], ['🍜', '라면 국수 ramen noodles'], ['🍣', '초밥 스시 sushi'], ['🍙', '주먹밥 rice ball'], ['🍚', '밥 rice'], ['🥟', '만두 dumpling'],
    ['🍗', '치킨 닭다리 chicken'], ['🍱', '도시락 bento lunch box'], ['🍰', '케이크 조각 cake'], ['🎂', '생일 케이크 birthday cake'], ['🍩', '도넛 donut'], ['🍪', '쿠키 cookie'], ['🍫', '초콜릿 chocolate'], ['🍿', '팝콘 popcorn'], ['☕', '커피 coffee'], ['🍵', '차 녹차 tea'],
    ['🧃', '주스 음료 juice box'], ['🥤', '음료 테이크아웃 drink cup'], ['🍺', '맥주 beer'], ['🍻', '건배 맥주 cheers beers'], ['🍷', '와인 wine']] },
  { key: 'activity', items: [['⚽', '축구 soccer football'], ['🏀', '농구 basketball'], ['⚾', '야구 baseball'], ['🎾', '테니스 tennis'], ['🏓', '탁구 ping pong'], ['⛳', '골프 golf'], ['🏆', '트로피 우승 trophy winner'], ['🥇', '금메달 1등 gold medal first'], ['🏅', '메달 medal'], ['🎮', '게임 game'],
    ['🎲', '주사위 dice'], ['🧩', '퍼즐 puzzle'], ['🎨', '그림 디자인 art palette design'], ['🎬', '영상 촬영 movie clapper video'], ['🎤', '마이크 노래 발표 microphone sing'], ['🎧', '헤드폰 음악 headphones'], ['🎹', '피아노 음악 piano music'], ['🎺', '트럼펫 팡파레 trumpet fanfare'], ['🎸', '기타 guitar'], ['🎁', '선물 gift present'],
    ['🎈', '풍선 balloon'], ['🎊', '축하 꽃가루 confetti'], ['🏃', '달리기 출발 run running'], ['🚶', '걷기 산책 walk'], ['💃', '춤 신남 dance'], ['🧘', '명상 요가 meditate yoga'], ['🏋️', '운동 헬스 workout gym'], ['✈️', '비행기 출장 여행 airplane flight travel'], ['🚗', '자동차 이동 car drive'], ['🚌', '버스 bus'],
    ['🚄', '기차 KTX train'], ['🚕', '택시 taxi cab'], ['🏠', '집 재택 home house'], ['🏢', '회사 사무실 office building'], ['🏖️', '휴가 해변 vacation beach'], ['⛰️', '산 등산 mountain hiking'], ['🧳', '짐 여행가방 luggage trip']] },
  { key: 'thing', items: [['🔥', '불 fire hot'], ['⭐', '별 star'], ['💯', '백점 100 hundred perfect'], ['❌', '엑스 no cross'], ['⚠️', '주의 warning'], ['❓', '물음 question'], ['❗', '느낌 exclamation'], ['📌', '핀 pin'], ['📎', '클립 clip'], ['🔗', '링크 link'], ['📝', '메모 memo note'], ['📅', '달력 calendar'], ['⏰', '시계 alarm time'], ['🚀', '로켓 rocket launch'], ['🐛', '버그 bug'], ['🔒', '잠금 lock'], ['💬', '말풍선 comment'],
    ['✨', '반짝 빛남 sparkles shine'], ['🌟', '빛나는 별 최고 glowing star'], ['💫', '어질 반짝 dizzy sparkle'], ['💥', '펑 충돌 boom collision'], ['💢', '화남 빡침 anger'], ['💦', '땀 물방울 sweat drops'], ['💤', '쿨쿨 잠 zzz sleep'], ['💰', '돈 돈주머니 money bag'], ['💸', '돈 지출 money spend'], ['💳', '카드 결제 credit card payment'],
    ['📦', '택배 상자 배송 package box delivery'], ['📞', '전화 phone call'], ['📱', '휴대폰 모바일 mobile phone'], ['💻', '노트북 컴퓨터 laptop computer'], ['🔍', '검색 찾기 search find'], ['🔑', '열쇠 키 key'], ['🔔', '알림 종 bell notification'], ['📍', '위치 장소 location place pin'], ['📚', '책 공부 books study'], ['✏️', '연필 수정 pencil edit'],
    ['📋', '목록 클립보드 clipboard list'], ['📁', '폴더 파일 folder file'], ['🗑️', '휴지통 삭제 trash delete'], ['⚙️', '설정 톱니 gear settings'], ['🔧', '렌치 수리 wrench fix'], ['🔨', '망치 빌드 hammer build'], ['🆘', '도움 긴급 sos help'], ['🚫', '금지 안됨 prohibited no'], ['🔄', '새로고침 반복 refresh repeat'], ['⭕', '동그라미 맞음 circle correct'], ['💎', '보석 가치 gem diamond']] },
];
export const ALL_EMOJI = EMOJI_GROUPS.flatMap((g) => g.items);
const KEY = 'argo-msgr-emoji-freq';
const readFreq = () => { try { return JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { return {}; } };
export function bumpEmoji(e) { try { const f = readFreq(); f[e] = (f[e] ?? 0) + 1; localStorage.setItem(KEY, JSON.stringify(f)); } catch { /* 저장 못 해도 동작 */ } }
/** 자주 쓴 순 n개 — 부족하면 기본값으로 채운다. */
export function topEmoji(n, defaults = ['✅', '👀', '👍', '🙏', '👏', '🎉', '❤️', '🔥', '💯']) { // 기본 9개 = 피커 한 줄을 채운다
  const f = readFreq(); const used = Object.entries(f).sort((a, b) => b[1] - a[1]).map(([e]) => e);
  return [...new Set([...used, ...defaults])].slice(0, n);
}
export function searchEmoji(q) { const s = q.trim().toLowerCase(); if (!s) return null; return ALL_EMOJI.filter(([e, k]) => e === s || k.toLowerCase().includes(s)).map(([e]) => e); }
