export const BROWSER_SPECS = Object.freeze([
  { name: 'browser_status', description: 'Check the actual browser provider, detected installation, separate agent login profile and work tab, and any Ego fallback reason. Does not open a browser or inspect accounts. Connect only the accounts needed for work in this agent browser on its execution device.',
    input_schema: { type: 'object', properties: {}, required: [] } },
  { name: 'browser_request_login', description: 'After navigating this work tab to the required service sign-in page, reserve that tab for the user to sign in on the browser execution device. Stops further browser automation in this run and keeps the tab open after the turn ends. One pending login tab per agent. Unavailable in headless browsers; mobile does not remotely control the execution device.',
    input_schema: { type: 'object', properties: {}, required: [] } },
  { name: 'browser_navigate', description: 'Open a URL in the Argo browser (dedicated Chrome profile) and wait for load. Returns title, url and a short text snapshot.',
    input_schema: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } },
  { name: 'browser_snapshot', description: 'Text snapshot of the current page: interactive elements get refs like [e3] for browser_click / browser_type, plus visible text. Use after navigation or actions.',
    input_schema: { type: 'object', properties: { max_chars: { type: 'number' } } } },
  { name: 'browser_click', description: 'Click an element by ref from browser_snapshot (e.g. "e3") or a CSS selector.',
    input_schema: { type: 'object', properties: { ref: { type: 'string' } }, required: ['ref'] } },
  { name: 'browser_type', description: 'Type text into an element by ref or CSS selector (focuses it first). Set submit=true to press Enter afterwards.',
    input_schema: { type: 'object', properties: { ref: { type: 'string' }, text: { type: 'string' }, submit: { type: 'boolean' } }, required: ['ref', 'text'] } },
  { name: 'browser_press', description: 'Press a keyboard key in the page: Enter, Tab, Escape, Backspace, ArrowDown, … Optional modifiers: "cmd+a", "ctrl+f".',
    input_schema: { type: 'object', properties: { key: { type: 'string' } }, required: ['key'] } },
  { name: 'browser_scroll', description: 'Scroll the page: direction up | down | top | bottom, amount in pixels (default 600).',
    input_schema: { type: 'object', properties: { direction: { type: 'string', enum: ['up', 'down', 'top', 'bottom'] }, amount: { type: 'number' } }, required: ['direction'] } },
  { name: 'browser_back', description: 'Go back in history.', input_schema: { type: 'object', properties: {} } },
  { name: 'browser_screenshot', description: 'Screenshot of the current viewport (PNG). Returned as an image when the model supports vision; the file is also saved under vault/screenshots/.',
    input_schema: { type: 'object', properties: {} } },
  { name: 'browser_eval', description: 'Run JavaScript in the page and return the result (JSON). Use for reading data the snapshot does not show.',
    input_schema: { type: 'object', properties: { js: { type: 'string' } }, required: ['js'] } },
]);
