// 아이콘 — Google Material Symbols Outlined(Apache 2.0) · FILL 0 · wght 400 · GRAD 0 · opsz 20. 유건 10/2: 구글 아이콘팩으로 통일.
// 글자는 앱이 쓰는 것만 뽑은 글꼴(ui/symbols.woff2, base.css @font-face)로 그린다 — 앱에 같이 실려 오프라인에서도 보이고, 그림 경로가 JS에 실리지 않는다.
// 이름 → Material 이름 표는 ui/icon-names.js, 글자표는 scripts/icon-font.mjs가 다시 쓴다(손으로 고치지 않는다).
const GLYPHS = {
  // <glyphs>
  home: '\ue9b2',
  eye: '\ue8f4',
  eyeOff: '\ue8f5',
  mail: '\ue159',
  inbox: '\ue156',
  send: '\ue163',
  draft: '\uf097',
  archive: '\ue149',
  doc: '\ue873',
  lock: '\ue899',
  stamp: '\ue982',
  run: '\uefd6',
  check: '\ue668',
  x: '\ue5cd',
  file: '\ue66d',
  book: '\ue86e',
  plus: '\ue145',
  search: '\uef7a',
  gear: '\ue8b8',
  trash: '\ue92e',
  dots: '\ue5d3',
  caret: '\ue5cf',
  chevron: '\ue5cc',
  back: '\ue5cb',
  grip: '\ue945',
  share: '\ue6b8',
  globe: '\uea07',
  link: '\ue250',
  copy: '\ue14d',
  reply: '\ue15e',
  hand: '\ue85e',
  width: '\uf730',
  sidebar: '\ue9e2',
  menu: '\ue5d2',
  layout: '\ue871',
  history: '\ue8b3',
  template: '\ue66b',
  resize: '\uf707',
  building: '\ue7ee',
  person: '\uf0d3',
  info: '\ue88e',
  refresh: '\ue5d5',
  chart: '\ue26b',
  box: '\uf720',
  tag: '\uf05b',
  receipt: '\uef6e',
  deal: '\ue8d4',
  megaphone: '\uef49',
  calendar: '\ue935',
  star: '\uf09a',
  sign: '\uf5a1',
  folder: '\ue2c7',
  target: '\ue719',
  upload: '\uf09b',
  download: '\uf090',
  pdf: '\ue415',
  image: '\ue3f4',
  pin: '\uf027',
  text: '\ue264',
  h1: '\uf85d',
  h2: '\uf85e',
  h3: '\uf85f',
  bullet: '\ue241',
  ordered: '\ue242',
  todo: '\ue6b1',
  quote: '\ue244',
  code: '\ue86f',
  divider: '\uf108',
  attach: '\ue226',
  expand: '\uf1ce',
  collapse: '\uf1cf',
  // </glyphs>
};

/** <i> — span이 아니라서 화면 css의 'X span' 선택자(검색 칸·접기 머리 등)에 걸리지 않는다(옛 svg와 같은 처지). 상자 크기 = size(px) — 옛 SVG와 같은 정사각형이라 자리가 바뀌지 않는다. 색은 currentColor(글자색)를 따른다 */
export function Icon({ name, size = 16, className = '', title }) {
  return <i className={`ico ${className}`} style={{ fontSize: size }} aria-hidden={title ? undefined : 'true'} role={title ? 'img' : undefined} aria-label={title} title={title}>{GLYPHS[name] ?? ''}</i>;
}
