'use client';
// 최소 법적 고지 — 이용약관 + 개인정보 처리방침. 무료 베타/데모 기준의 평이한 안내다.
// 정식 유료 전환 시 변호사 검토를 받은 정식본으로 교체해야 한다(이 페이지는 초안 성격).
import Link from 'next/link';
import { useLang } from '../i18n';

const CONTACT = process.env.NEXT_PUBLIC_ARGO_CONTACT || '';
const UPDATED = '2026-07-13';

export default function LegalPage() {
  const { lang } = useLang();
  const ko = lang === 'ko';
  const S = ({ title, children }) => (
    <section style={{ display: 'grid', gap: 6 }}>
      <h2 style={{ fontSize: 15, fontWeight: 700, margin: '10px 0 0' }}>{title}</h2>
      <div style={{ fontSize: 13, color: 'var(--fg-2)', lineHeight: 1.7 }}>{children}</div>
    </section>
  );
  return (
    <div style={{ minHeight: '100vh', display: 'grid', placeItems: 'start center', padding: '40px 24px' }}>
      <div className="card fade-up" style={{ width: 'min(720px, 100%)', padding: '34px 34px', display: 'grid', gap: 4 }}>
        <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 12 }}>
          <h1 style={{ fontSize: 22, fontWeight: 750, margin: 0 }}>{ko ? '약관 및 개인정보' : 'Terms & Privacy'}</h1>
          <Link href="/login" style={{ fontSize: 13, color: 'var(--fg-3)' }}>{ko ? '← 로그인' : '← Sign in'}</Link>
        </div>
        <p style={{ fontSize: 12, color: 'var(--fg-3)', margin: '2px 0 8px' }}>
          {ko ? `최종 업데이트 ${UPDATED} · 무료 베타 기준 안내(초안). 정식 서비스 시 갱신됩니다.`
              : `Last updated ${UPDATED} · Free-beta notice (draft). Will be updated for general release.`}
        </p>

        {ko ? (
          <>
            <S title="1. 서비스 개요">
              Argo는 사용자의 기기에서 실행되는 로컬 우선(local-first) AI 크루 도구입니다. 회사 데이터(대화·기억·설정)는
              기본적으로 사용자의 기기 폴더에 저장되며, 기기 간 동기화를 켠 경우에만 사용자가 지정한 저장소로 전송됩니다.
            </S>
            <S title="2. AI 생성물 고지">
              크루의 답변·문서·결정은 AI(대규모 언어모델)가 생성한 것으로, 오류나 부정확이 있을 수 있습니다. 중요한 판단은
              반드시 사람이 검토하세요. 되돌리기 어렵거나 외부로 나가는 행동은 결재(승인) 절차를 거치도록 설계되어 있습니다.
            </S>
            <S title="3. 키·자격 증명(BYOK)">
              사용자가 연결한 AI 러너의 API 키·로그인 토큰은 사용자의 기기(회사 폴더의 보안 파일)에만 저장되며, 화면·로그에는
              마스킹되어 표시됩니다. Argo 운영자는 이 값을 수집하지 않습니다. 사용량 요금은 각 AI 제공자와 사용자 간에 발생합니다.
            </S>
            <S title="4. 수집·처리 정보">
              인증을 켠 경우 로그인 이메일과 세션 정보가 인증 제공자(Supabase)를 통해 처리됩니다. 그 외 회사 콘텐츠는 로컬 저장이
              원칙입니다. 동기화·클라우드 기능을 켜면 해당 데이터가 사용자가 지정한 저장소로 이전될 수 있습니다.
            </S>
            <S title="5. 책임의 한계">
              무료 베타 기간 동안 서비스는 “있는 그대로” 제공되며, 특정 목적 적합성이나 무중단·무오류를 보장하지 않습니다.
              데이터는 정기적으로 백업하시기를 권장합니다.
            </S>
            <S title="6. 문의">
              {CONTACT
                ? <>서비스·개인정보 관련 문의: <a href={`mailto:${CONTACT}`}>{CONTACT}</a></>
                : '문의처는 운영자 설정 후 표시됩니다.'}
            </S>
          </>
        ) : (
          <>
            <S title="1. Overview">
              Argo is a local-first AI-crew tool that runs on your device. Company data (chats, memory, settings) is stored in
              folders on your device by default, and is sent to a store you designate only if you enable cross-device sync.
            </S>
            <S title="2. AI-generated content">
              Crew replies, documents, and decisions are generated by AI (large language models) and may contain errors. Always
              review important outputs. Actions that are hard to reverse or leave the company go through an approval step by design.
            </S>
            <S title="3. Keys & credentials (BYOK)">
              API keys and login tokens for the runners you connect are stored only on your device (a secured file in the company
              folder) and are masked in the UI and logs. The Argo operator does not collect them. Usage charges are between you and
              each AI provider.
            </S>
            <S title="4. Information processed">
              If authentication is enabled, your sign-in email and session are processed via the auth provider (Supabase). Other
              company content stays local by default. Enabling sync/cloud features may transfer that data to a store you designate.
            </S>
            <S title="5. Limitation of liability">
              During the free beta the service is provided “as is,” without warranty of fitness for a particular purpose or of
              uninterrupted, error-free operation. Please back up your data regularly.
            </S>
            <S title="6. Contact">
              {CONTACT
                ? <>Questions about the service or privacy: <a href={`mailto:${CONTACT}`}>{CONTACT}</a></>
                : 'A contact address appears once the operator sets it.'}
            </S>
          </>
        )}
      </div>
    </div>
  );
}
