import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const artifacts=new URL('../artifacts/dm-delegation/',import.meta.url);await mkdir(artifacts,{recursive:true});
const results=[];
// 1:1 수신·참조 = 입력창 명령(유건 결정 2026-09-14): @이름(또는 /to 고르기) = 수신, /cc 고르기 = 참조 칩. 별도 패널 없음.
for(const engine of (process.env.DM_ENGINE ? [process.env.DM_ENGINE] : ['chromium','webkit'])){
 const browser=await ({chromium,webkit}[engine]).launch({headless:true,...(engine==='chromium'?{channel:'chrome'}:{})});
 for(const lang of ['ko','en']) for(const width of [390,1280]){
  const page=await browser.newPage({viewport:{width,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
  await page.addInitScript(lang=>localStorage.setItem('argo-lang',lang),lang);
  const reload=lang==='ko'?'다시 불러오기':'Reload recipients';const send=lang==='ko'?'보내기':'Send';
  const ta=page.locator('.msgr-composer textarea');const option=name=>page.locator('.msgr-rolepop [role=option]').filter({hasText:name});
  const pick=async(cmd,name)=>{await ta.fill(cmd);await option(name).click();await ta.evaluate(el=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}; // 선택 뒤 앱이 다음 프레임에 커서를 끝으로 옮긴다 — 곧바로 fill 하면 전체 선택이 풀려 덧붙여진다(간헐 실패 원인)
  try{
   await page.goto(`http://127.0.0.1:${process.env.DM_TEST_PORT || 5201}/test/dm-lifecycle.fixture.html?recipientFailure`);
   await page.locator('[data-sec="dms"] .item').filter({hasText:'Fixture Existing Agent'}).click();
   await ta.fill('/cc');
   await page.locator('.msgr-rolepop').getByRole('button',{name:reload}).waitFor();
   await ta.fill('Ordinary DM while recipient loading failed');
   await page.getByRole('button',{name:send,exact:true}).click();
   await page.waitForFunction(()=>window.__dmFixture.tables.msgr_messages.some(m=>m.body==='Ordinary DM while recipient loading failed'));
   await ta.fill('/cc');
   await page.locator('.msgr-rolepop').getByRole('button',{name:reload}).click();
   await option('Fixture New Agent').waitFor();
   assert.equal(await option('Fixture Outdated Agent').isDisabled(),true);
   assert.equal(await option('Fixture Unknown Agent').isDisabled(),true);
   assert.equal(await page.getByRole('button',{name:send,exact:true}).isDisabled(),true,'a bare /cc command cannot be sent (send button is the only path on phones)');
   await ta.fill('/cc outdated');await option('Fixture Outdated Agent').waitFor();await ta.press('Enter');
   assert.equal(await page.locator('.msgr-cc-chips').count(),0,'Enter on an unsupported agent adds nothing');assert.equal(await ta.inputValue(),'/cc outdated','…and keeps the command');
   await ta.fill('/cc fixture new');await option('Fixture New Agent').waitFor();assert.equal(await option('Fixture Outdated Agent').count(),0,'multi-word query keeps filtering');
   await ta.fill('/cc');await option('Fixture New Agent').waitFor();
   assert.ok(Number(await option('Fixture Outdated Agent').evaluate(el=>getComputedStyle(el).opacity))<1,'unsupported rows are visibly dimmed');
   await ta.press('ArrowDown');assert.match(await page.locator('.msgr-rolepop [role=option][aria-selected="true"]').textContent(),/Fixture Existing Agent/,'ArrowDown moves the highlight to the next enabled row');
   await ta.press('ArrowDown');await ta.press('Enter');
   await page.locator('.msgr-cc-chips .msgr-chan').filter({hasText:'Fixture New Agent'}).waitFor({timeout:5000}).catch(()=>{throw new Error('ArrowDown must skip unsupported rows (New → Existing → New)');});
   await page.getByRole('button',{name:lang==='ko'?'Fixture New Agent 수신자 해제':'Remove recipient Fixture New Agent'}).click();
   await ta.fill('/cc outdated');await option('Fixture Outdated Agent').waitFor();assert.equal(await page.locator('.msgr-rolepop [role=option][aria-selected="true"]').count(),0,'a list of only unsupported rows has no highlighted row');
   await ta.fill('/cc nobody');await page.locator('.msgr-rolepop .empty').waitFor();assert.equal(await option('Fixture').count(),0,'unmatched query shows the no-match hint');
   await ta.fill('/');await page.locator('.msgr-slashpop').waitFor();
   assert.deepEqual((await page.locator('.msgr-slashpop .cmd').allTextContents()).slice(0,2),['/to','/cc'],'DM commander offers /to·/cc first');
   await ta.fill('/cc');
   assert.equal(await option('Fixture Existing Agent').count(),1,'/cc keeps the DM partner (context only)');
   await ta.fill('/to');
   assert.equal(await option('Fixture Existing Agent').count(),0,'/to drops the DM partner (already the addressee)');
   await page.evaluate(()=>{window.__dmFixture.upgraded=true;});
   await ta.fill('/cc');await page.locator('.msgr-rolepop').getByRole('button',{name:reload}).click();
   await page.waitForFunction(()=>[...document.querySelectorAll('.msgr-rolepop [role=option]')].some(b=>b.textContent.includes('Fixture Outdated Agent')&&!b.disabled));
   await pick('/cc','Fixture New Agent');
   await page.locator('.msgr-cc-chips .msgr-chan').filter({hasText:'Fixture New Agent'}).waitFor();
   assert.equal(await ta.inputValue(),'','picking a CC clears the command');
   await page.evaluate(()=>{window.__dmFixture.readiness={'crew-new':false};});
   await ta.fill('/cc');await page.locator('.msgr-rolepop').getByRole('button',{name:reload}).click();
   await page.locator('.msgr-dm-delivery-warning').waitFor();
   await ta.fill('Readiness changed after selection');
   assert.equal(await page.getByRole('button',{name:send,exact:true}).isDisabled(),true);
   await page.getByRole('button',{name:lang==='ko'?'Fixture New Agent 수신자 해제':'Remove recipient Fixture New Agent'}).click();
   await page.waitForFunction(()=>!document.querySelector('.msgr-dm-delivery-warning'));
   assert.equal(await page.getByRole('button',{name:send,exact:true}).isEnabled(),true);
   await page.evaluate(()=>{window.__dmFixture.readiness={'crew-new':true};});
   await ta.fill('/cc');await page.locator('.msgr-rolepop').getByRole('button',{name:reload}).click();
   await page.waitForFunction(()=>[...document.querySelectorAll('.msgr-rolepop [role=option]')].some(b=>b.textContent.includes('Fixture New Agent')&&!b.disabled));
   await pick('/cc','Fixture Existing Agent');
   await pick('/to new','Fixture New Agent');
   assert.equal(await ta.inputValue(),'@Fixture New Agent ','/to inserts the mention like @');
   await ta.fill('@Fixture New Agent Delegate with inline name');
   await page.screenshot({path:new URL(`${engine}-${lang}-${width}-selected.png`,artifacts).pathname});
   const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);
   const chip=await page.locator('.msgr-cc-chips .msgr-chan').boundingBox();assert.ok(chip.x>=0&&chip.x+chip.width<=width);
   const before=await page.evaluate(()=>structuredClone(window.__dmFixture.tables.msgr_channel_members));
   await page.getByRole('button',{name:send,exact:true}).click();
   await page.waitForFunction(()=>window.__dmFixture.tables.msgr_messages.some(m=>m.body==='@Fixture New Agent Delegate with inline name'));
   const sent=await page.evaluate(()=>window.__dmFixture.tables.msgr_messages.find(m=>m.body==='@Fixture New Agent Delegate with inline name'));
   assert.deepEqual(sent.mentions,[{kind:'crew',id:'crew-new'},{kind:'crew',id:'crew-existing',role:'cc'}],'inline mention stays role-less (server = to), CC chip carries role');
   assert.deepEqual(await page.evaluate(()=>window.__dmFixture.tables.msgr_channel_members),before);
   await page.locator('.msgr-message-recipients').filter({hasText:'Fixture Existing Agent'}).waitFor();
   assert.equal(await page.locator('.msgr-cc-chips').count(),0,'chips clear after send');
   await ta.fill('@all current DM only');
   await page.getByRole('button',{name:send,exact:true}).click();
   await page.waitForFunction(()=>window.__dmFixture.tables.msgr_messages.some(m=>m.body==='@all current DM only'));
   const all=await page.evaluate(()=>window.__dmFixture.tables.msgr_messages.find(m=>m.body==='@all current DM only').mentions);
   assert.equal(all.some(m=>m.id==='crew-new'),false);assert.equal(all.some(m=>m.id==='crew-existing'),true);
   await pick('/cc','Fixture New Agent');
   await ta.fill('Context only to new agent');
   await page.getByRole('button',{name:send,exact:true}).click();
   await page.waitForFunction(()=>window.__dmFixture.tables.msgr_messages.some(m=>m.body==='Context only to new agent'));
   assert.deepEqual(await page.evaluate(()=>window.__dmFixture.tables.msgr_messages.find(m=>m.body==='Context only to new agent').mentions),[{kind:'crew',id:'crew-new',role:'cc'}]);
   await ta.fill('/cc');await ta.press('Escape');assert.equal(await ta.inputValue(),'','Escape drops the command');
   if(width<720)await page.getByRole('button',{name:lang==='ko'?'홈으로':'Home',exact:true}).click();
   await page.locator('[data-sec="channels"] .item').filter({hasText:'Fixture Private'}).click();
   await ta.fill('/');await page.locator('.msgr-slashpop').waitFor();
   assert.deepEqual((await page.locator('.msgr-slashpop .cmd').allTextContents()).slice(0,2),['/to','/cc'],'channels offer /to·/cc too (messenger feature, not DM-only — 유건 2026-09-14)');
   assert.equal(await page.locator('.msgr-slashpop .tag').count(),0,'no crew-list column in the commander (it overflowed the window)');
   const popBox=await page.locator('.msgr-slashpop').boundingBox();const compBox=await page.locator('.msgr-composer').boundingBox();
   assert.ok(popBox.x+popBox.width<=width&&(width<720||popBox.x+popBox.width<=compBox.x+compBox.width+1),'commander never leaves the viewport; on desktop it stays within the composer width');
   await ta.fill('/cc');await option('Fixture Existing Agent').waitFor();
   assert.equal(await option('Fixture New Agent').count(),0,'channel /cc lists only crews of that channel');
   await option('Fixture Existing Agent').click();await page.locator('.msgr-cc-chips .msgr-chan').filter({hasText:'Fixture Existing Agent'}).waitFor();
   await ta.fill('Channel CC only');await page.getByRole('button',{name:send,exact:true}).click();
   await page.waitForFunction(()=>window.__dmFixture.tables.msgr_messages.some(m=>m.body==='Channel CC only'&&m.channel_id==='private'));
   assert.deepEqual(await page.evaluate(()=>window.__dmFixture.tables.msgr_messages.find(m=>m.body==='Channel CC only'&&m.channel_id==='private').mentions),[{kind:'crew',id:'crew-existing',role:'cc'}],'channel CC = mention with role cc (bridge/server skip cc for execution)');
   await ta.fill('@F');assert.ok(await page.locator('.msgr-pop [role=option]').count()>=1,'channel @mention popup still works');
   await ta.fill('@Fixture New Agent');
   await page.getByRole('button',{name:send,exact:true}).click();
   await page.waitForFunction(()=>window.__dmFixture.tables.msgr_messages.some(m=>m.body==='@Fixture New Agent'&&m.channel_id==='private'));
   assert.deepEqual(await page.evaluate(()=>window.__dmFixture.tables.msgr_messages.find(m=>m.body==='@Fixture New Agent'&&m.channel_id==='private').mentions),[],'private candidate scope unchanged');
   assert.deepEqual(errors,[]);results.push({engine,lang,width,pass:true});console.log('PASS',engine,lang,width);
  }catch(e){results.push({engine,lang,width,pass:false,error:e.message});console.error('FAIL',engine,lang,width,e.stack);await page.screenshot({path:new URL(`${engine}-${lang}-${width}-failure.png`,artifacts).pathname});}
  await page.close();
 }
 await browser.close();
}
await writeFile(new URL('results.json',artifacts),JSON.stringify(results,null,2));
if(results.some(r=>!r.pass))process.exitCode=1;
